# -*- coding: utf-8 -*-
"""Investment_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZuBzXq821bYscqaLz6BsNGNEvHgYZKu
"""

"""
!pip install -U langgraph "langchain[openai]"
!pip install -qU langchain-core langchain-openai langchain-community
!pip install -U langchain pydantic
!pip install langgraph
!pip install yfinance
"""
!pip install -qU langchain-core langchain-openai langchain-community
import os
import uuid
import yfinance as yf
import gradio as gr
from typing import Annotated, TypedDict, List, Dict, Any, Optional
from dotenv import load_dotenv

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain_community.tools.yahoo_finance_news import YahooFinanceNewsTool
from langchain_community.utilities import GoogleSerperAPIWrapper

from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph.message import add_messages
from langgraph.channels.last_value import LastValue

# --- Configuration & API Keys ---

try:
    with open("/content/LangSmith API.txt", "r") as f:
        os.environ["LANGCHAIN_API_KEY"] = f.read().strip()
    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    os.environ["LANGCHAIN_PROJECT"] = "My-AI-Investor"
except FileNotFoundError:
    print("LangSmith API key file not found. Skipping tracing setup.")

try:
    with open("/content/Serper APIkey.txt", "r") as f:
        os.environ["SERPER_API_KEY"] = f.read().strip()
except FileNotFoundError:
    print("Serper API key file not found.")

try:
    with open("/content/OpenAIKey.txt", "r") as f:
        api_key = f.read().strip()
except FileNotFoundError:

    api_key = os.environ.get("OPENAI_API_KEY", "")

# --- Tools Definition ---

@tool
def news_yh_search(ticker: str):
    """Find additional financial news about a stock
    Args:
          ticker: The ticker of a company in order to find news about it """
    # YahooFinanceNewsTool wrapper
    tool_instance = YahooFinanceNewsTool()
    return tool_instance.run(f"{ticker}")

serper = GoogleSerperAPIWrapper()

@tool
def get_fin_data(ticker: str):
    """Find financial data about a stock including financials, balance sheet and cashflow.
    Args:
          ticker: The ticker of a company you are looking for"""
    stock = yf.Ticker(ticker)

    try:
        fin_data = stock.financials.to_string()
        fin_data += "\n" + stock.balance_sheet.to_string()
        fin_data += "\n" + stock.cashflow.to_string()
        return fin_data
    except Exception as e:
        return f"Error fetching financial data: {e}"

@tool
def serper_search(ticker: str):
    """Find general financial news about a stock using Google Search
    Args:
          ticker: The ticker of a company in order to find news about it """
    return serper.run(f"Find financial data and news about {ticker}")

tools = [get_fin_data, serper_search, news_yh_search]

# --- LLM Setup ---

llm = ChatOpenAI(
    model_name="mistralai/devstral-2512:free",
    openai_api_key=api_key,
    openai_api_base="https://openrouter.ai/api/v1",
    temperature=0.0
)

llm_with_tools = llm.bind_tools(tools)

# --- State Definition ---

class Fin_State(TypedDict):
    ticker: str
    financials: Annotated[str, LastValue]
    news: Annotated[List[str], "merge_list_handler"]
    summary: Annotated[str, LastValue]
    sentiment: Annotated[str, LastValue]
    report: Annotated[str, LastValue]
    messages: Annotated[List[Any], add_messages]

# --- Nodes ---

def data_fetch(state: Fin_State):
    """
    Decides which tools to call.
    Removed FetcherOutput and with_structured_output.
    Now simply returns the AI message with tool_calls.
    """
    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are an AI financial analyst. You MUST use the available tools to gather:
        - Financial statements (balance sheet, cash flow) for {ticker} using the 'get_fin_data' tool.
        - Latest news for {ticker} using 'serper_search' or 'news_yh_search'.

        Return the tool calls necessary to get this information. Do not output the final report yet."""),
        ("human", "Gather complete financial data and latest news for {ticker} stock.")
    ])

    chain = prompt | llm_with_tools
    response = chain.invoke({"ticker": state["ticker"]})

    return {"messages": [response]}

def process_tool_results(state: Fin_State) -> Fin_State:
    """
    Extracts data from ToolMessages and updates the specific state keys
    (financials, news) so the summarizer can use them easier.
    """
    messages = state["messages"]
    new_fin = state.get("financials", "")
    new_news = state.get("news", [])


    for m in reversed(messages):
        if isinstance(m, ToolMessage):

            if m.name == 'get_fin_data':
                new_fin = m.content

            elif m.name in ['news_yh_search', 'serper_search']:

                if m.content not in new_news:
                    new_news.append(m.content)
        elif isinstance(m, AIMessage):

            break

    return {"financials": new_fin, "news": new_news}

def sum_fin_report(state: Fin_State) -> Fin_State:

    fin_data = state.get('financials', 'No financial data available.')

    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a financial analyst that summarizes financial data."),
        ('user', f"Make a summary about this company's financial data:\n\n{fin_data}")
    ])

    chain = prompt | llm
    summary = chain.invoke(state).content
    return {"summary": summary}

def sentiment_analysis(state: Fin_State) -> Fin_State:
    news_list = state.get('news', [])
    news_text = '\n'.join(news_list) if news_list else "No recent news found."

    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a news sentiment analyst. Classify news as positive, neutral, or negative."),
        ("user", "Analyze sentiment of the following news articles:\n\n{news}")
    ])

    chain = prompt | llm
    sentiment = chain.invoke({'news': news_text}).content
    return {"sentiment": sentiment}

def report_analyst(state: Fin_State) -> Fin_State:

    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are a Senior Investment Analyst (CFA) at a top-tier hedge fund.
        Your goal is to produce a deep-dive, institutional-grade investment memorandum.

        ### Tone & Style Guidelines:
        - **Professional:** Use Wall Street terminology (e.g., "YOY growth," "margin expansion," "solvency ratios").
        - **Data-Driven:** Avoid vague adjectives. Back every claim with a specific number or percentage.
        - **Visuals:** You MUST use Markdown tables to present financial data. Text should analyze the tables, not repeat them.

        ### Required Structure:

        1. **Executive Summary**: A high-level synthesis of the investment thesis (Bull/Bear/Neutral).

        2. **Financial Matrices (Markdown Tables)**:
           - **Income Statement Highlights**: Revenue, Gross Profit, Net Income, EPS (Last 3 periods if available).
           - **Balance Sheet Health**: Cash, Total Assets, Total Liabilities, Debt-to-Equity Ratio.
           - **Cash Flow Analysis**: Operating Cash Flow, CapEx, Free Cash Flow.

        3. **Sentiment & Market Context**: Analyze the provided news sentiment. Are market expectations aligned with fundamentals?

        4. **Key Risks & Catalysts**:
           - **Downside Risks**: What could break the thesis?
           - **Upside Catalysts**: What could drive the stock higher?

        5. **Final Verdict**: Clear Buy/Hold/Sell recommendation with a price target justification (based on P/E or growth).
        """),
        ("user", """DATA CONTEXT:

        --- RAW FINANCIALS ---
        {financials}

        --- NEWS SENTIMENT ---
        {sentiment}

        --- SUMMARY NOTES ---
        {summary}

        Create the final Institutional Investment Report now.""")
    ])

    chain = prompt | llm
    report = chain.invoke(state).content
    return {"report": report}

# --- Graph Construction ---

builder = StateGraph(Fin_State)

builder.add_node('data_fetch', data_fetch)
builder.add_node('tools', ToolNode(tools=tools))
builder.add_node('process_tools', process_tool_results)
builder.add_node('sum_fin_report', sum_fin_report)
builder.add_node('sentiment_analysis', sentiment_analysis)
builder.add_node('report_analyst', report_analyst)

builder.add_edge(START, 'data_fetch')


builder.add_conditional_edges(
    'data_fetch',
    tools_condition,
    {
        "tools": "tools",
        END: "sum_fin_report"
    }
)


builder.add_edge('tools', 'process_tools')
builder.add_edge('process_tools', 'sum_fin_report')

builder.add_edge('sum_fin_report', 'sentiment_analysis')
builder.add_edge('sentiment_analysis', 'report_analyst')
builder.add_edge('report_analyst', END)

graph = builder.compile()

def analyze_stock(ticker):
    initial_state = {
        "ticker": ticker,
        "financials": "",
        "news": [],
        "summary": "",
        "sentiment": "",
        "report": "",
        "messages": [HumanMessage(content=f"Find financial data and latest news for {ticker}")]
    }

    report_content = ""


    for msg, metadata in graph.stream(initial_state, stream_mode="messages"):


        if metadata.get("langgraph_node") == "report_analyst":


            if msg.content:
                report_content += msg.content

                yield report_content



if __name__ == "__main__":

    try:
        from IPython.display import Image, display
        display(Image(graph.get_graph().draw_mermaid_png()))
    except:
        pass


    with gr.Blocks(css="#report-box { min-height: 500px; background-color: #000; color: #fff; padding: 15px; }") as iface:
        gr.Markdown("## 🧠 AI Investment Analyst")

        with gr.Row():
            ticker_in = gr.Textbox(label="Enter Stock Ticker (e.g., AAPL)")

        submit_btn = gr.Button("Analyze")
        report_out = gr.Markdown(label="Investment Report", elem_id="report-box")


        submit_btn.click(fn=analyze_stock, inputs=ticker_in, outputs=report_out)

    iface.launch()