version: '3.8'

services:
  backend:
    build: ./backend
    container_name: finbot-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # <--- WE CHANGED THIS LINE
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: finbot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped